#ifndef _DEFS_H_
#define _DEFS_H_


#define FILE_DATA_CACHE_NUM_OF_ENTRIES 4
#define FILE_DATA_CACHE_SIZE_OF_ENTRY 2
#define FILE_INDEX_CACHE_NUM_OF_ENTRIES 2
#define FILE_INDEX_CACHE_SIZE_OF_ENTRY 1
#define OPEN_FILES_TABLE_SIZE 30
#define PARTITION_CACHE_NUM_OF_ENTRIES 128
#define PARTITION_CACHE_SIZE_OF_ENTRY 4
#define PARTITION_CACHE_LRU_REQUEST_BUFFER_SIZE 30

#endif